spring.application.name=order-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

server.port=8081

resilience4j.ratelimiter.instances.productRatelimiter.limitForPeriod=2
resilience4j.ratelimiter.instances.productRatelimiter.limitRefreshPeriod=10
resilience4j.ratelimiter.instances.productRatelimiter.timeOutDuration=1
